from enum import Enum


class FeedbackStatus(str, Enum):
    RECEIVED = "RECEIVED"
    PROCESSED = "PROCESSED"


class IssueStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    PROCESSING = "PROCESSING"
    ROUTED = "ROUTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    CLOSED = "CLOSED"


class EventType(str, Enum):
    FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED"
    FEEDBACK_CLASSIFIED = "FEEDBACK_CLASSIFIED"
    ISSUE_CREATED = "ISSUE_CREATED"
    ISSUE_ROUTED = "ISSUE_ROUTED"
    REPORTER_ACKNOWLEDGED = "REPORTER_ACKNOWLEDGED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    REPORTER_NOTIFIED = "REPORTER_NOTIFIED"
    CONFIRMATION_REQUESTED = "CONFIRMATION_REQUESTED"
    REPORTER_CONFIRMED = "REPORTER_CONFIRMED"
    ISSUE_CLOSED = "ISSUE_CLOSED"


class NotificationStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class Department(str, Enum):
    ACADEMIC_AFFAIRS = "Academic Affairs"
    IT = "IT"
    FACILITIES = "Facilities"
    ADMINISTRATION = "Administration"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
